language: cpp
compiler:
  - clang
  - gcc
env:
  matrix:
  - OPENMP=1 MPICPP=mpic++
  - OPENMP=1
  - OPENMP=0 MPICPP=mpic++
  - OPENMP=0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-numpy python-scipy python-matplotlib
  - sudo apt-get install -y openmpi-bin libopenmpi-dev
script: 
 - export OMPI_CXX=$CXX
 - make executable -j 4 OPENMP=$OPENMP CPP=$MPICPP
 - export OMP_NUM_THREADS=4
